# Generated by Django 3.2 on 2020-12-07 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wowModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corp_cust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.DecimalField(decimal_places=0, max_digits=32)),
            ],
            options={
                'db_table': 'corp_cust',
            },
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('corp_id', models.AutoField(primary_key=True, serialize=False)),
                ('corp_name', models.CharField(max_length=32)),
                ('corp_reg_num', models.CharField(max_length=20)),
                ('corp_discount', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'corporation',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=32)),
                ('lname', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=50)),
                ('zipcode', models.DecimalField(decimal_places=0, max_digits=5)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('cust_type', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Indi_cust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_num', models.CharField(max_length=15)),
                ('insur_com_name', models.CharField(max_length=32)),
                ('insur_polic_num', models.CharField(max_length=12)),
                ('coupon', models.ManyToManyField(blank=True, null=True, to='wowModel.Coupon')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wowModel.customer')),
            ],
            options={
                'db_table': 'indi_cust',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('idate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=50)),
                ('zipcode', models.DecimalField(decimal_places=0, max_digits=5)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdate', models.DateField()),
                ('method', models.CharField(max_length=10)),
                ('card_num', models.DecimalField(decimal_places=0, max_digits=32)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowModel.customer')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wowModel.invoice')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Rental_Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('start_odo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('end_odo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('odo_limit', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowModel.customer')),
                ('do_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_location_id', to='wowModel.location')),
                ('pu_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pu_location_id', to='wowModel.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rental_record',
            },
        ),
        migrations.CreateModel(
            name='Veh_class',
            fields=[
                ('class_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=32)),
                ('rental_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.DecimalField(decimal_places=0, max_digits=8, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('vin', models.CharField(max_length=17)),
                ('lp_num', models.CharField(max_length=10)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowModel.veh_class')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowModel.location')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='rental_record',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowModel.vehicle'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wowModel.rental_record'),
        ),
        migrations.AddField(
            model_name='corp_cust',
            name='corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowModel.corporation'),
        ),
        migrations.AddField(
            model_name='corp_cust',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wowModel.customer'),
        ),
    ]
