# Generated by Django 3.2 on 2020-12-06 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wowModel', '0004_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=32)),
                ('lname', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=50)),
                ('zipcode', models.DecimalField(decimal_places=0, max_digits=5)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('cust_type', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
