# Generated by Django 3.2 on 2020-12-06 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wowModel', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=50)),
                ('zipcode', models.DecimalField(decimal_places=0, max_digits=5)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Veh_class',
            fields=[
                ('class_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=32)),
                ('rental_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cid',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.DecimalField(decimal_places=0, max_digits=8, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('vin', models.CharField(max_length=17)),
                ('lp_num', models.CharField(max_length=10)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowModel.veh_class')),
                ('location', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wowModel.location')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='Rental_Record',
            fields=[
                ('record_id', models.DecimalField(decimal_places=0, max_digits=8, primary_key=True, serialize=False)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('start_odo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('end_odo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('odo_limit', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('do_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_location_id', to='wowModel.location')),
                ('pu_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pu_location_id', to='wowModel.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowModel.vehicle')),
            ],
            options={
                'db_table': 'rental_record',
            },
        ),
    ]
