# Generated by Django 3.2 on 2020-12-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowModel', '0006_auto_20201206_1403'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
